mongodb-org-server vs. mongodb-server

diff --git a/default_configs/etc/init.d/mongod b/default_configs/etc/init.d/mongod
--- a/default_configs/etc/init.d/mongod
+++ b/default_configs/etc/init.d/mongod
@@ -20,7 +20,7 @@
 # Suite 330, Boston, MA 02111-1307 USA
 #
 ### BEGIN INIT INFO
-# Provides:          mongodb
+# Provides:          mongod
 # Required-Start:    $network $local_fs $remote_fs
 # Required-Stop:     $network $local_fs $remote_fs
 # Should-Start:      $named
@@ -32,7 +32,7 @@
 #                    document-oriented data store that's easy to deploy, manage
 #                    and use. It's network accessible, written in C++ and offers
 #                    the following features:
-#                    .
+#
 #                       * Collection oriented storage - easy storage of object-
 #                         style data
 #                       * Full index support, including on inner objects
@@ -40,10 +40,8 @@
 #                       * Replication and fail-over support
 #                       * Efficient storage of binary data including large
 #                         objects (e.g. videos)
-#                       * Auto-sharding for cloud-level scalability (Q209)
-#                    .
-#                    This package is build with V8 JavaScript engine.
-#                    .
+#                       * Automatic partitioning for cloud-level scalability
+#
 #                    High performance, scalability, and reasonable depth of
 #                    functionality are the goals for the project.
 ### END INIT INFO
@@ -52,16 +50,20 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/bin/mongod
 DESC=database
 
-# Default defaults.  Can be overridden by the /etc/default/$NAME
-NAME=mongodb
-CONF=/etc/mongodb.conf
-RUNDIR=/var/run/mongodb
-PIDFILE=$RUNDIR/$NAME.pid
-ENABLE_MONGODB=yes
+NAME=mongod
+# Defaults.  Can be overridden by the /etc/default/$NAME
+# Other configuration options are located in $CONF file. See here for more:
+# http://dochub.mongodb.org/core/configurationoptions
+CONF=/etc/mongod.conf
+PIDFILE=/var/run/$NAME.pid
+ENABLE_MONGOD=yes
 
-# Include mongodb defaults if available
+# Include mongodb defaults if available.
+# All variables set before this point can be overridden by users, by
+# setting them directly in the defaults file. Use this to explicitly
+# override these values, at your own risk.
 if [ -f /etc/default/$NAME ] ; then
-	. /etc/default/$NAME
+        . /etc/default/$NAME
 fi
 
 # Handle NUMA access to CPUs (SERVER-3574)
@@ -76,25 +78,26 @@ else
     DAEMON_OPTS="-- "${DAEMON_OPTS:-"--config $CONF"}
 fi
 
+
 if test ! -x $DAEMON; then
     echo "Could not find $DAEMON"
     exit 0
 fi
 
-if test "x$ENABLE_MONGODB" != "xyes"; then
+if test "x$ENABLE_MONGOD" != "xyes"; then
     exit 0
 fi
 
 . /lib/lsb/init-functions
 
 STARTTIME=1
-DIETIME=10                   # Time to wait for the server to die, in seconds
+DIETIME=10                  # Time to wait for the server to die, in seconds
                             # If this value is set too low you might not
                             # let some servers to die gracefully and
                             # 'restart' will not work
 
 DAEMONUSER=${DAEMONUSER:-mongodb}
-DAEMON_OPTS=${DAEMON_OPTS:-"--unixSocketPrefix=$RUNDIR --config $CONF run"}
+DAEMONGROUP=${DAEMONGROUP:-mongodb}
 
 set -e
 
@@ -122,13 +125,31 @@ running() {
 }
 
 start_server() {
-            test -e "$RUNDIR" || install -m 755 -o mongodb -g mongodb -d "$RUNDIR"
-# Start the process using the wrapper
+            # Recommended ulimit values for mongod or mongos
+            # See http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
+            #
+            ulimit -f unlimited
+            ulimit -t unlimited
+            ulimit -v unlimited
+            ulimit -n 64000
+            ulimit -m unlimited
+            ulimit -l unlimited
+
+            # In dash, ulimit takes -p for maximum user processes
+            # In bash, it's -u
+            if readlink /proc/$$/exe | grep -q dash
+            then
+                    ulimit -p 64000
+            else
+                    ulimit -u 64000
+            fi
+
+            # Start the process using the wrapper
             start-stop-daemon --background --start --quiet --pidfile $PIDFILE \
-                        --make-pidfile --chuid $DAEMONUSER \
+                        --make-pidfile --chuid $DAEMONUSER:$DAEMONGROUP \
                         --exec $NUMACTL $DAEMON $DAEMON_OPTS
             errcode=$?
-	return $errcode
+        return $errcode
 }
 
 stop_server() {
@@ -138,32 +159,32 @@ stop_server() {
                         --user $DAEMONUSER \
                         --exec $DAEMON
             errcode=$?
-	return $errcode
+        return $errcode
 }
 
 force_stop() {
 # Force the process to die killing it manually
-	[ ! -e "$PIDFILE" ] && return
-	if running ; then
-		kill -15 $pid
-	# Is it really dead?
-		sleep "$DIETIME"s
-		if running ; then
-			kill -9 $pid
-			sleep "$DIETIME"s
-			if running ; then
-				echo "Cannot kill $NAME (pid=$pid)!"
-				exit 1
-			fi
-		fi
-	fi
-	rm -f $PIDFILE
+        [ ! -e "$PIDFILE" ] && return
+        if running ; then
+                kill -15 $pid
+        # Is it really dead?
+                sleep "$DIETIME"s
+                if running ; then
+                        kill -9 $pid
+                        sleep "$DIETIME"s
+                        if running ; then
+                                echo "Cannot kill $NAME (pid=$pid)!"
+                                exit 1
+                        fi
+                fi
+        fi
+        rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC" "$NAME"
+        log_daemon_msg "Starting $DESC" "$NAME"
         # Check if it's running first
         if running ;  then
             log_progress_msg "apparently already running"
@@ -186,12 +207,12 @@ case "$1" in
             # Either we could not start it
             log_end_msg 1
         fi
-	;;
+        ;;
   stop)
         log_daemon_msg "Stopping $DESC" "$NAME"
         if running ; then
             # Only stop the server if we see it running
-			errcode=0
+                        errcode=0
             stop_server || errcode=$?
             log_end_msg $errcode
         else
@@ -207,14 +228,14 @@ case "$1" in
         if running; then
             # If it's still running try to kill it more forcefully
             log_daemon_msg "Stopping (force) $DESC" "$NAME"
-			errcode=0
+                        errcode=0
             force_stop || errcode=$?
             log_end_msg $errcode
         fi
-	;;
+        ;;
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
-		errcode=0
+                errcode=0
         stop_server || errcode=$?
         # Wait some sensible amount, some server need this
         [ -n "$DIETIME" ] && sleep $DIETIME
@@ -222,7 +243,7 @@ case "$1" in
         [ -n "$STARTTIME" ] && sleep $STARTTIME
         running || errcode=$?
         log_end_msg $errcode
-	;;
+        ;;
   status)
 
         log_daemon_msg "Checking status of $DESC" "$NAME"
@@ -242,10 +263,10 @@ case "$1" in
         ;;
 
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+        N=/etc/init.d/$NAME
+        echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+        exit 1
+        ;;
 esac
 
 exit 0
